---
- name: Hello Events
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 2
  rules:
    - name: Debug
      condition: event.i == 2
      action:
        debug:
          msg: "Hello"
    - name: Run job
      condition: false
      action:
        run_job_template:
          name: print_job_project
          organization: Default
